flowchart TD
%% generated in 0.01s
    urirun_connector_kvm__backends["urirun_connector_kvm.backends<br/>72 funcs"]
    urirun_connector_kvm__cdp["urirun_connector_kvm.cdp<br/>16 funcs"]
    urirun_connector_kvm__launch_backends["urirun_connector_kvm.launch_backends<br/>12 funcs"]
    urirun_connector_kvm__launch_backends ==>|6| urirun_connector_kvm__backends
    urirun_connector_kvm__launch_backends -->|2| urirun_connector_kvm__cdp
    urirun_connector_kvm__cdp -->|1| urirun_connector_kvm__backends
